### ISSUE TITLE
Add school name and grade to Student model

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/attendance#6]
I'm not sure if school name is better as a free-form field, or if it should be preloaded from some data source. Additionally, I'm curious if grade is actually useful to record, since it would change every year in most cases?

**Comment by andrewscollins** [comment]
Interesting, i'd like to hear more about this since it's related to a next mentor feature I was going to propose ..... that every submission would get tagged with some sort of indicator (their school or library name, or if at-home their location). This will help mentors key in on the submissions they are supposed to be claiming based on their pairings. 

Is this the same thing or a different ticket? @cgreim would the issue I described above make sense to implement now as a fix before pairings are automatized through the home screen page? 

Andrew

**Comment by cgreim** [comment]
@andrewscollins this is a ticket for the attendance app (the new keytag). I don't think we've discussed a feature like this for CM -- feel free to open a ticket there to discuss!

**Comment by andrewscollins** [comment]
oh ok! sorry was way off : ) ... will open a new ticket related to what I described above

**Comment by cgreim** [comment]
haha yea no worries! you were probably auto-subscribed to this repository, but you can change your notifications with that "Watch" button on the top right.
